version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: service_catalog
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  
  service-catalog:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_USER: appuser
      DB_PASSWORD: apppassword
      DB_NAME: service_catalog

volumes:
  mysql_data:
